version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  flask-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: production
    depends_on:
      - postgres
